@startuml

Persona *-- Direccion
Persona *-- Genero

Viaje o-- "*" Persona
Viaje *-- Direccion

CalculadoraDeDistancia *-- AdapterDistancia
AdapterDistancia <|.. AdapterDistanceMatrixAPI
AdapterDistancia ..> Direccion

Notificador *-- TipoDeNotificacion
TipoDeNotificacion <|.. NotificarSolicitudDeCuidado
TipoDeNotificacion <|.. NotificarComienzoDeCuidado
TipoDeNotificacion <|.. NotificarFinDeCuidado
TipoDeNotificacion ..> Viaje

ManejadorDeIncidente *-- RespuestaAIncidente
RespuestaAIncidente <|.. AlertarCuidadores
RespuestaAIncidente <|.. LlamarALaPolicia
RespuestaAIncidente <|.. LlamarAlCelularDelUsuario
RespuestaAIncidente <|.. EsperarPorSiEsUnaFalsaAlarma
RespuestaAIncidente ..> Viaje

CalculadoraDeTiempoDeDemora ..> Direccion


class Persona {
 -nombre: String
 -apellido: String
 -domicilio: Direccion
 -fechaNacimiento: LocalDate
 -genero: Genero
 -notificacionesHabilitadas: Boolean
 -celular: String
 -cantidadDeMinutosPorFalsaAlarma: Integer
}

class Direccion{
 -calle: String
 -altura: String
 -piso: String
}

class Genero{
 -nombre: String
}

class Viaje{
 -transeunte: Persona
 -cuidadores: List<Persona>
 -destinoInicial: Direccion
 -destinoFinal: Direccion
 -tiempoDeDemoraAproximadoEnMinutosCalculado: Integer
 -distanciaEnKMEntreDestinosCalculada: Double
}

class CalculadoraDeTiempoDeDemora{
 +calcularTiempoDeDemoraAproximadoEnMinutos(Direccion destinoInicial, Direccion destinoFinal): Integer
}

class CalculadoraDeDistancia{
 -adapterDistancia: AdapterDistancia
 +calcularDistanciaEnKMEntre(Direccion destinoInicial, Direccion destinoFinal): Double
}

interface AdapterDistancia{
 +calcularDistanciaEnKMEntre(Direccion destinoInicial, Direccion destinoFinal): Double
}

class AdapterDistanceMatrixAPI{
 -distanceMatrixAPI: DistanceMatrixAPI
 +calcularDistanciaEnKMEntre(Direccion destinoInicial, Direccion destinoFinal): Double
}

class Notificador{
 -tipoDeNotificacion: TipoDeNotificacion
 +notificarCuidadores(Viaje): void
}

interface TipoDeNotificacion{
 +notificarCuidadores(Viaje): void
}

class NotificarSolicitudDeCuidado{
 +notificarCuidadores(Viaje): void
}

class NotificarComienzoDeCuidado{
 +notificarCuidadores(Viaje): void
}

class NotificarFinDeCuidado{
 +notificarCuidadores(Viaje): void
}

class ManejadorDeIncidente{
 -respuestaAIncidente: RespuestaAIncidente
 +responderFrenteAIncidente(Viaje): void
}

interface RespuestaAIncidente{
 +responderFrenteAIncidente(Viaje): void
}

class AlertarCuidadores{
 +responderFrenteAIncidente(Viaje): void
}

class LlamarALaPolicia{
 +responderFrenteAIncidente(Viaje): void
}

class LlamarAlCelularDelUsuario{
 +responderFrenteAIncidente(Viaje): void
}

class EsperarPorSiEsUnaFalsaAlarma{
 +responderFrenteAIncidente(Viaje): void
}

@enduml